# Generated by Django 4.2.7 on 2025-08-02 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='토픽명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '토픽',
                'verbose_name_plural': '토픽들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='카테고리명')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='색상')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.topic', verbose_name='토픽')),
            ],
            options={
                'verbose_name': '토픽 카테고리',
                'verbose_name_plural': '토픽 카테고리들',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TopicMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', '관리자'), ('member', '멤버'), ('viewer', '뷰어')], default='member', max_length=20, verbose_name='역할')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='가입일')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.topic', verbose_name='토픽')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '토픽 멤버',
                'verbose_name_plural': '토픽 멤버들',
                'unique_together': {('topic', 'user')},
            },
        ),
    ]
